import React from "react";

export const infosData = [
    {
      nom: "REGION GRAND EST",
      telephone: "03 83 18 87 00",
      courriel: "mrs.accueil@grandest.fr",
      batimentEtage: "G/2",
    },
    {
      nom: "ASPTT COMITE REGIONAL GRAND EST",
      telephone: "03 83 18 87 43",
      courriel: "comitegrandest@asptt.com",
      batimentEtage: "D/4",
    },
    {
      nom: "ATHLETISME LIGUE REGIONALE GRAND EST",
      telephone: "03 83 18 87 77",
      courriel: "contact@athlelarge.fr",
      batimentEtage: "D/4",
    },
    {
      nom: "AVIRON LIGUE REGIONALE GRAND EST",
      telephone: "03 83 18 95 59",
      courriel: "Lr06@ffaviron.fr",
      batimentEtage: "D/1",
    },
    {
      nom: "BADMINTON LIGUE REGIONALE GRAND EST",
      telephone: "03 83 18 88 41",
      courriel: "contact@lgebad.com",
      batimentEtage: "D/0",
    },
    {
      nom: "BASKET LIGUE REGIONALE GRAND EST",
      telephone: "03 83 18 95 02",
      courriel: "secretariat@lrgeb.fr",
      batimentEtage: "G/1",
    },
    {
      nom: "CANOE KAYAK COMITE REGIONAL GRAND EST",
      telephone: "03 83 18 88 39",
      courriel: "grandest@ffck.org",
      batimentEtage: "D/3",
    },
    {
      nom: "COURSE D'ORIENTATION LIGUE REGIONALE GRAND EST",
      telephone: "03 83 18 87 65",
      courriel: "lgeco@gmx.fr",
      batimentEtage: "D/1",
    },
    {
      nom: "CRESS GRAND EST",
      telephone: "03 83 18 87 39",
      courriel: "contact@cress-grandest.org",
      batimentEtage: "D/0",
    },
    {
      nom: "CROS GRAND EST",
      telephone: "03 83 18",
      courriel: "grandest@franceolympique.com",
      batimentEtage: "G/2",
    },
    {
      nom: "CYCLISME COMITE REGIONAL GRAND EST",
      telephone: "03 83 18 87 59",
      courriel: "ffcgrandest.comite@orange.fr",
      batimentEtage: "D/0",
    },
    {
      nom: "EQUITATION COMITE REGIONAL GRAND EST",
      telephone: "03 83 18 87 52",
      courriel: "contact@cregrandest.fr",
      batimentEtage: "D/4",
    },
    {
      nom: "EPGV COMITE REGIONAL GRAND EST",
      telephone: "03 83 18 87 27",
      courriel: "grandest@comite-epgv.fr",
      batimentEtage: "D/4",
    },
    {
      nom: "EPGV COMITE DEPARTEMENTAL MEURTHE ET MOSELLE",
      telephone: "03 83 18 88 27",
      courriel: "codep-gv54@epgv.fr",
      batimentEtage: "D/2",
    },
    {
      nom: "ESCRIME LIGUE REGIONALE GRAND EST",
      telephone: "03 83 18 87 40",
      courriel: "administration@crege.fr",
      batimentEtage: "D/1",
    },
    {
      nom: "FNMNS",
      telephone: "03 83 18 87 57",
      courriel: "fnmns.org@wanadoo.fr",
      batimentEtage: "D/4",
    },
    {
      nom: "FNMNS CNF",
      telephone: "03 83 18 88 37",
      courriel: "secretariat-cnfnmns@outlook.fr",
      batimentEtage: "D/4",
    },
    {
      nom: "GOLF LIGUE REGIONALE GRAND EST",
      telephone: "03 83 18 95 34",
      courriel: "contact@ligue-golfgrandest.org",
      batimentEtage: "D/3",
    },
    {
      nom: "GYMNASTIQUE COMITE REGIONAL GRAND EST",
      telephone: "03 83 18 87 84",
      courriel: "contact@ffgymgrandest.fr",
      batimentEtage: "D/1",
    },
    {
      nom: "HANDBALL LIGUE REGIONALE GRAND EST",
      telephone: "03 83 18 87 10",
      courriel: "5600000@ffhandball.net",
      batimentEtage: "D/3",
    },
    {
      nom: "HANDBALL COMITE DEPARTEMENTAL MEURTHE ET MOSELLE",
      telephone: "03 83 18 88 10",
      courriel: "5654000@ffhandball.net",
      batimentEtage: "D/1",
    },
    {
      nom: "HANDISPORT COMITE REGIONAL GRAND EST",
      telephone: "03 83 18 87 45",
      courriel: "grandest@handisport.org",
      batimentEtage: "G/0",
    },
    {
      nom: "HANDISPORT COMITE DEPARTEMENTAL MEURTHE ET MOSELLE",
      telephone: "03 83 18 87 48",
      courriel: "cd54@handisport.org",
      batimentEtage: "G/0",
    },
    {
      nom: "JUDO LIGUE REGIONALE GRAND EST",
      telephone: "03 83 18 87 64",
      courriel: "judograndest@gmail.com",
      batimentEtage: "G/2",
    },
    {
      nom: "JUDO COMITE DEPARTEMENTAL MEURTHE ET MOSELLE",
      telephone: "03 83 18 88 29",
      courriel: "secretariat@cd54judo.fr",
      batimentEtage: "D/4",
    },
    {
      nom: "LORRAINE MOUVEMENT ASSOCIATIF",
      telephone: "03 83 18 88 38",
      courriel: "lma@lorrainemouvementassociatif.com",
      batimentEtage: "G/2",
    },
    {
      nom: "MOTOCYCLISME LIGUE REGIONALE GRAND EST",
      telephone: "03 83 18 87 68",
      courriel: "contact@liguemotograndest.fr",
      batimentEtage: "D/1",
    },
    {
      nom: "NATATION LIGUE REGIONALE GRAND EST",
      telephone: "03 83 18 87 32",
      courriel: "secretariat@lge-natation.fr",
      batimentEtage: "D/0",
    },
    {
      nom: "COMITE PARALYMPIQUE ET SPORTIF Français",
      telephone: "03 83 18 87 08",
      courriel: "contact@france-paralympique.fr",
      batimentEtage: "G/2",
    },
    {
      nom: "PETANQUE COMITE DEPARTEMENTAL MEURTHE ET MOSELLE",
      telephone: "03 83 18 88 31",
      courriel: "cd54@petanque.fr",
      batimentEtage: "D/3",
    },
    {
      nom: "RANDONNEE PEDESTRE COMITE REGIONAL GRAND EST",
      telephone: "03 83 18 87 36",
      courriel: "grand-est@ffrandonnee.fr",
      batimentEtage: "D/3",
    },
    {
      nom: "RANDONNEE PEDESTRE COMITE DEPARTEMENTAL MEURTHE ET MOSELLE",
      telephone: "03 83 18 95 58",
      courriel: "meurthe-et-moselle@ffrandonnee.fr",
      batimentEtage: "D/3",
    },
    {
      nom: "RUGBY LIGUE REGIONALE GRAND EST",
      telephone: "03 83 18 95 80",
      courriel: "contacts@lrger.fr",
      batimentEtage: "D/2",
    },
    {
      nom: "SPELEOLOGIE LIGUE REGIONALE GRAND EST",
      telephone: "03 83 18 95 10",
      courriel: "christophe.prevot@ffspeleo.fr",
      batimentEtage: "D/1",
    },
    {
      nom: "SPORT ADAPTE LIGUE REGIONALE GRAND EST",
      telephone: "03 83 18 87 71",
      courriel: "antoine.mion@sportadapte.fr",
      batimentEtage: "D/3",
    },
    {
      nom: "SPORT AUTOMOBILE LIGUE REGIONALE GRAND EST",
      telephone: "03 83 18 87 94",
      courriel: "ligue03@wanadoo.fr",
      batimentEtage: "D/1",
    },
    {
      nom: "SPORT POUR TOUS COMITE REGIONAL GRAND EST",
      telephone: "03 83 18 88 22",
      courriel: "cr.grandest@sportspourtous.org",
      batimentEtage: "D/3",
    },
    {
      nom: "TAEKWONDO LIGUE REGIONALE GRAND EST",
      telephone: "03 83 18 88 43",
      courriel: "contact@taekwondograndest.fr",
      batimentEtage: "D/2",
    },
    {
      nom: "TENNIS LIGUE REGIONALE GRAND EST",
      telephone: "03 83 67 60 10",
      courriel: "ligue.grandest@fft.fr",
      batimentEtage: "G/1",
    },
    {
      nom: "TENNIS DE TABLE LIGUE REGIONALE GRAND EST",
      telephone: "03 83 18 87 87",
      courriel: "contact@lgett.fr",
      batimentEtage: "D/2",
    },
    {
      nom: "TRIATHLON LIGUE REGIONALE GRAND EST",
      telephone: "03 83 18 88 03",
      courriel: "contact@triathlongrandest.fr",
      batimentEtage: "G/1",
    },
    {
      nom: "UNSS",
      telephone: "03 83 18 87 29",
      courriel: "sr-nancy-metz@unss.org",
      batimentEtage: "D/1",
    },
    {
      nom: "VOLLEY BALL LIGUE REGIONALE GRAND EST",
      telephone: "03 83 18 87 22",
      courriel: "fmoiny.lgevolley@gmail.com",
      batimentEtage: "D/2",
    },
    {
      nom: "UGSEL 54",
      telephone: "03 83 18 87 09",
      courriel: "ugselsport54@gmail.com",
      batimentEtage: "D/1",
    },
  ];
  